### ISSUE TITLE
Issue Terminating Console Application

### ISSUE THREAD

**Issue by NLandry91** [mtconnect/dot_net_sdk#1]
Hi,

Has anyone had the following error using this library:
"Exception occurred waiting for connection: A blocking operation was interrupted by a call to WSACancelBlockingCall"

I am initializing the adapter object (MTConnect.Adapter) in the main thread and then using the SendChanged() method in a C# task. See below:

```
public void StartAdapter()
        {
            runLoop = true;
            adapter.Start();
            machine.Connect();
            mainTask = new Task(() =>
            {
                RunLoop();
            });
            mainTask.Start();
        }

        private void RunLoop()
        {
            while (runLoop) {
                try
                {
                    GetCurrentMachineData(machine);
                    mode.Value = machine.Mode;
                    execution.Value = machine.Status;
                    program.Value = machine.Program;
                    state.Value = machine.State;
                    spindleOverride.Value = machine.OverrideValues.speedOverride;
                    feedOverride.Value = machine.OverrideValues.feedOverride;
                    rapidOverride.Value = machine.OverrideValues.rapidOverride;
                    //errorState.Value = machine
                    //errorMessage.Value = machine.ErrorList[0].errorDescription;

                    //Update adapter stream
                    adapter.SendChanged();

                    System.Threading.Thread.Sleep(pauseTime);
                }
                catch
                {
                    Console.WriteLine("Machine is not connected");
                    System.Threading.Thread.Sleep(10 * pauseTime);
                }
            }
        }

        public void StopAdapter()
        {
            machine.Disconnect();
            adapter.Stop();
            
        }

        protected void CancelHandler(object sender, ConsoleCancelEventArgs args)
        {
            runLoop = false;
            mainTask.Wait();
            StopAdapter();
        }
```

CancelHandler is subscribed to Console.CancelKeyPress

I'm getting the WSACancelBlockingCall exception at 
`mListenThread.Join(2000);`

![capture](https://cloud.githubusercontent.com/assets/8760347/25005978/23f544f2-2029-11e7-9804-f0c3f36877a8.JPG)

Any suggestions?

**Comment by wsobel** [comment]
Looks like stop was called. I have not seen this issue. The exception is because stop was called and the adapter is shutting down. 

Why was stop called?

(Sent from mobile)

**Comment by NLandry91** [comment]
I want to be able to terminate gracefully (closing the machine connection and stopping the adapter) with CTRL-C.

**Comment by wsobel** [comment]
The problem is stop is called in the middle of send. If you first stop your thread and wait for it to exit with a join and then shut down the adapter, that should fix the issue. 

(Sent from mobile)

**Comment by NLandry91** [comment]
Hmmmm. I'm a bit confused because I thought that I was doing that (see code example above) with first calling mainTask.Wait(), then I call my method StopAdapter(). Am I missing something?

**Comment by NLandry91** [comment]
I created a pull request that fixes this issue.

**Comment by wsobel** [comment]
Thanks a lot, just merged.

Best Regards,
Will Sobel
